In [1]:
import numpy as np, matplotlib.pyplot as plt, pandas as pd
from vivarium import Artifact
from get_draws.api import get_draws

#pd.set_option('display.max_rows', 8)
!date

%load_ext autoreload
%autoreload 2

Tue Oct 24 12:01:37 PDT 2023

# Vivarium Artifact Exploration

Creating an automated way to test some of the PAf artifacts for general errors or issues.

In [21]:
locations_1 = ['alabama'
               ,'alaska','arizona','arkansas','california','colorado','connecticut','delaware',
             'district_of_columbia','florida','georgia','hawaii','idaho','illinois','indiana','iowa',
            'kansas','kentucky','louisiana','maine','maryland','massachusetts','michigan','minnesota','mississippi']

locations_2 = ['missouri','montana','nebraska','nevada','new_hampshire','new_jersey','new_mexico','new_york',
             'north_carolina','north_dakota','ohio','oklahoma','oregon','pennsylvania','rhode_island']

locations_3 = ['south_carolina','south_dakota','tennessee','texas','utah','vermont','virginia','washington',
             'west_virginia','wisconsin','wyoming']

risks = ['high_systolic_blood_pressure', 'high_ldl_cholesterol', 'high_body_mass_index_in_adults']

outcomes = ['acute_myocardial_infarction', 'post_myocardial_infarction_to_acute_myocardial_infarction', 'acute_ischemic_stroke','chronic_ischemic_stroke_to_acute_ischemic_stroke','heart_failure_from_ischemic_heart_disease','heart_failure_residual']

ages = [25.0, 30.0, 35.0, 40.0, 45.0, 50.0, 55.0, 60.0, 65.0, 70.0, 75.0, 80.0, 85.0, 90.0, 95.0]

sexes = ['Female', 'Male']

In [3]:
ls /mnt/team/simulation_science/costeffectiveness/artifacts/vivarium_nih_us_cvd/51-locations/v3-20231019

alabama.hdf               logs/               ohio.hdf
alaska.hdf                louisiana.hdf       oklahoma.hdf
arizona.hdf               maine.hdf           oregon.hdf
arkansas.hdf              maryland.hdf        paf_calculation/
california.hdf            massachusetts.hdf   pennsylvania.hdf
colorado.hdf              michigan.hdf        rhode_island.hdf
connecticut.hdf           minnesota.hdf       south_carolina.hdf
delaware.hdf              mississippi.hdf     south_dakota.hdf
district_of_columbia.hdf  missouri.hdf        tennessee.hdf
florida.hdf               montana.hdf         texas.hdf
georgia.hdf               nebraska.hdf        utah.hdf
hawaii.hdf                nevada.hdf          vermont.hdf
idaho.hdf                 new_hampshire.hdf   virginia.hdf
illinois.hdf              new_jersey.hdf      washington.hdf
indiana.hdf               new_mexico.hdf      west_virginia.hdf
iowa.hdf                  new_york.hdf        wisconsin.hdf
kansas.hdf                north_carolina.hdf  wyoming.hdf
kentucky.hdf              north_dakota.hdf

In [14]:
def load_artifact_data(locations):
    master_art_data = pd.DataFrame()
    for location in locations: 
        art = Artifact(f'/mnt/team/simulation_science/costeffectiveness/artifacts/vivarium_nih_us_cvd/51-locations/v3-20231019/{location}.hdf', 
                   filter_terms=['year_start == 2019', 'age_start >=  25']) # << MIGHT WANT TO CHANGE THESE TERMS
    
        data = art.load('risk_factor.joint_mediated_risks.population_attributable_fraction')
        data['location'] = location
    
        master_art_data = master_art_data.append(data)
        
    return master_art_data

## Load Artifact Data

In [22]:
PAF_Values_1 = load_artifact_data(locations_1)

/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)

In [23]:
PAF_Values_2 = load_artifact_data(locations_2)

/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)

In [24]:
PAF_Values_3 = load_artifact_data(locations_3)

/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)
/tmp/ipykernel_2527807/3230333457.py:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  master_art_data = master_art_data.append(data)

### Test for Zero Values

In [6]:
def test_zero(pafs, draws, locations):
    zero_values = pd.DataFrame()
    pafs.reset_index(inplace=True)
    for draw in draws: 
        for i in locations: 
            for j in risks: 
                for k in outcomes: 
                    for m in ages: 
                        for n in sexes: 
                            subdata = pafs.loc[(pafs.location == i) & (pafs.risk == j) & (pafs.affected_entity == k) & (pafs.age_start == m) & (pafs.sex == n)]
                            loc = i
                            risk = j
                            outcome = k
                            age = m
                            sex = n
                            draw = draw
                            if not subdata.loc[subdata[draw] == 0].empty:
                                zero_values_temp = pd.DataFrame([loc,risk,outcome,age,sex,draw]).transpose()
                                zero_values = pd.concat([zero_values,zero_values_temp], ignore_index=True)
    zero_values.rename(columns={0:'location',1:'risk',2:'outcome',3:'age',4:'sex',5:'draw'}, inplace=True)
    return zero_values

In [6]:
draw_test = list(PAF_Values_1.columns)

In [11]:
paf_zeros_1 = test_zero(PAF_Values_1, draw_test, locations_1)

In [12]:
paf_zeros_1.head()

,location,risk,outcome,age,sex,draw
0,hawaii,high_body_mass_index_in_adults,acute_ischemic_stroke,80.0,Female,draw_0
1,hawaii,high_body_mass_index_in_adults,acute_ischemic_stroke,80.0,Male,draw_0
2,hawaii,high_body_mass_index_in_adults,acute_ischemic_stroke,85.0,Female,draw_0
3,hawaii,high_body_mass_index_in_adults,acute_ischemic_stroke,85.0,Male,draw_0
4,hawaii,high_body_mass_index_in_adults,acute_ischemic_stroke,90.0,Female,draw_0

In [ ]:
paf_zeros_2 = test_zero(PAF_Values_2, draw_test, locations_2)

In [ ]:
paf_zeros_3 = test_zero(PAF_Values_3, draw_test, locations_3)

In [ ]:
paf_zeros_1.to_csv('/ihme/homes/lutzes/paf_zero_values_1.csv')

In [ ]:
paf_zeros_2.to_csv('/ihme/homes/lutzes/paf_zero_values_2.csv')

In [ ]:
paf_zeros_3.to_csv('/ihme/homes/lutzes/paf_zero_values_3.csv')

### Old Test for Zero Values 
Not designed to track all but instead to spot test

In [16]:
PAF_Values_1#.columns

                                                                                                                    draw_0  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.774599
                                             acute_myocardial_infarction                        incidence_rate    0.858888
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.774599
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.232291
                                             heart_failure_residual                             incidence_rate    0.232291
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.753488
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.455401
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.406097
                                             heart_failure_residual                             incidence_rate    0.406097
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.753488

                                                                                                                    draw_1  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.878868
                                             acute_myocardial_infarction                        incidence_rate    0.908147
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.878868
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.196803
                                             heart_failure_residual                             incidence_rate    0.196803
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.736745
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.539355
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.352198
                                             heart_failure_residual                             incidence_rate    0.352198
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.736745

                                                                                                                    draw_2  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.940032
                                             acute_myocardial_infarction                        incidence_rate    0.913682
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.940032
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.209816
                                             heart_failure_residual                             incidence_rate    0.209816
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.734012
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.503416
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.322594
                                             heart_failure_residual                             incidence_rate    0.322594
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.734012

                                                                                                                    draw_3  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.939584
                                             acute_myocardial_infarction                        incidence_rate    0.907021
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.939584
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.216658
                                             heart_failure_residual                             incidence_rate    0.216658
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.683757
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.479501
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.310569
                                             heart_failure_residual                             incidence_rate    0.310569
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.683757

                                                                                                                    draw_4  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.933927
                                             acute_myocardial_infarction                        incidence_rate    0.920091
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.933927
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.210350
                                             heart_failure_residual                             incidence_rate    0.210350
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.718415
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.425321
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.361195
                                             heart_failure_residual                             incidence_rate    0.361195
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.718415

                                                                                                                    draw_5  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.787717
                                             acute_myocardial_infarction                        incidence_rate    0.895689
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.787717
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.147338
                                             heart_failure_residual                             incidence_rate    0.147338
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.789950
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.585172
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.399259
                                             heart_failure_residual                             incidence_rate    0.399259
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.789950

                                                                                                                    draw_6  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.920561
                                             acute_myocardial_infarction                        incidence_rate    0.923494
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.920561
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.273309
                                             heart_failure_residual                             incidence_rate    0.273309
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.745411
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.680810
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.359187
                                             heart_failure_residual                             incidence_rate    0.359187
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.745411

                                                                                                                    draw_7  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.898879
                                             acute_myocardial_infarction                        incidence_rate    0.891703
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.898879
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.274335
                                             heart_failure_residual                             incidence_rate    0.274335
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.477492
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.540069
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.327135
                                             heart_failure_residual                             incidence_rate    0.327135
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.477492

                                                                                                                    draw_8  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.857236
                                             acute_myocardial_infarction                        incidence_rate    0.952234
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.857236
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.243650
                                             heart_failure_residual                             incidence_rate    0.243650
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.718543
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.576772
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.379466
                                             heart_failure_residual                             incidence_rate    0.379466
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.718543

                                                                                                                    draw_9  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.896135
                                             acute_myocardial_infarction                        incidence_rate    0.910197
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.896135
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.242972
                                             heart_failure_residual                             incidence_rate    0.242972
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.723525
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.572304
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.388055
                                             heart_failure_residual                             incidence_rate    0.388055
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.723525

                                                                                                                  ...  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure  ...
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    ...
                                             acute_myocardial_infarction                        incidence_rate    ...
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   ...
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    ...
                                             heart_failure_residual                             incidence_rate    ...
...                                                                                                               ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    ...
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   ...
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    ...
                                             heart_failure_residual                             incidence_rate    ...
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   ...

                                                                                                                  draw_991  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.841247
                                             acute_myocardial_infarction                        incidence_rate    0.913827
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.841247
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.208561
                                             heart_failure_residual                             incidence_rate    0.208561
...                                                                                                                    ...
Male   95.0      125.0   2019       2020     acute_myocardial_infarction                        incidence_rate    0.753389
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.419861
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.360772
                                             heart_failure_residual                             incidence_rate    0.360772
                                             post_myocardial_infarction_to_acute_myocardial_... transition_rate   0.753389

                                                                                                                  draw_992  \
sex    age_start age_end year_start year_end affected_entity                                    affected_measure
Female 25.0      30.0    2019       2020     acute_ischemic_stroke                              incidence_rate    0.850296
                                             acute_myocardial_infarction                        incidence_rate    0.901992
                                             chronic_ischemic_stroke_to_acute_ischemic_stroke   transition_rate   0.850296
                                             heart_failure_from_ischemic_heart_disease          incidence_rate    0.266771
                                             heart_failure_residual                             incidence_rate    0.266771

In [9]:
draw_test = ['draw_1','draw_2','draw_3','draw_4','draw_5','draw_12','draw_15','draw_27','draw_45','draw_68','draw_92',
             'draw_125','draw_134','draw_111','draw_101','draw_129','draw_189','draw_166','draw_130',
             'draw_250','draw_333','draw_310','draw_387','draw_324','draw_308','draw_498','draw_451','draw_452','draw_453',
             'draw_675','draw_676','draw_677',
             'draw_500','draw_550',]
#draw_test = PAF_Values_1.draw.unique()

In [19]:
def test_zero(draws):
    for draw in draws: 
        subdata = PAF_Values_1
        draw = draw
        #if subdata.loc[subdata[draw] == 0].empty:
        #    print(draw)
        if not subdata.loc[subdata[draw] == 0].empty:
            print(draw)

In [25]:
test_zero(PAF_Values_1.columns)

In [26]:
test_zero(PAF_Values_2.columns)

In [27]:
test_zero(PAF_Values_3.columns)

In [77]:
PAF_small = PAF_Values_1.loc[(PAF_Values_1.risk == 'high_body_mass_index_in_adults') & (PAF_Values_1.location == 'illinois') & (PAF_Values_1.draw_5 == 0)]
PAF_small.std(axis=1)

/tmp/ipykernel_3501384/3153386477.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  PAF_small.std(axis=1)

sex     age_start  age_end  year_start  year_end  affected_entity                                   affected_measure
Female  80.0       85.0     2019        2020      acute_ischemic_stroke                             incidence_rate      0.048773
        85.0       90.0     2019        2020      acute_ischemic_stroke                             incidence_rate      0.043971
        90.0       95.0     2019        2020      acute_ischemic_stroke                             incidence_rate      0.039361
        95.0       125.0    2019        2020      acute_ischemic_stroke                             incidence_rate      0.036759
Male    80.0       85.0     2019        2020      acute_ischemic_stroke                             incidence_rate      0.042867
        85.0       90.0     2019        2020      acute_ischemic_stroke                             incidence_rate      0.037772
        90.0       95.0     2019        2020      acute_ischemic_stroke                             incidence_rate      0.033623
        95.0       125.0    2019        2020      acute_ischemic_stroke                             incidence_rate      0.031016
Female  80.0       85.0     2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.048773
        85.0       90.0     2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.043971
        90.0       95.0     2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.039361
        95.0       125.0    2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.036759
Male    80.0       85.0     2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.042867
        85.0       90.0     2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.037772
        90.0       95.0     2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.033623
        95.0       125.0    2019        2020      chronic_ischemic_stroke_to_acute_ischemic_stroke  transition_rate     0.031016
dtype: float64

In [ ]:
## Test to see if GBD has a similar standard deviation

In [81]:
pafs = get_draws(gbd_id_type=['rei_id', 'cause_id'], gbd_id=[370, 495], source='burdenator', measure_id=2, metric_id=2, year_id=2019, gbd_round_id=6, status='best', decomp_step='step5')
pafs

/ihme/homes/lutzes/.conda/envs/cvd_eng/lib/python3.8/site-packages/get_draws/api.py:187: UserWarning: No version_id was specified, so get_draws will automatically determine a best version ID to use from the given parameters. If you want to retrieve a specific version please pass a version_id directly.
  warnings.warn(

,age_group_id,cause_id,draw_0,draw_1,draw_10,draw_100,draw_101,draw_102,draw_103,draw_104,...,draw_997,draw_998,draw_999,location_id,measure_id,metric_id,rei_id,sex_id,year_id,version_id
0,9,495,0.412271,0.103432,0.373925,0.453553,0.323010,0.125783,0.068041,0.245991,...,0.458273,0.401400,0.269704,216,2,2,370,1,2019,130
1,10,495,0.549657,0.154062,0.691752,0.520858,0.403314,0.169686,0.090063,0.328389,...,0.522089,0.515780,0.327617,216,2,2,370,1,2019,130
2,11,495,0.499192,0.122006,0.440361,0.665597,0.415843,0.185417,0.220364,0.467107,...,0.311634,0.194943,0.639762,216,2,2,370,1,2019,130
3,12,495,0.482668,0.229599,0.478812,0.493080,0.284473,0.241982,0.146425,0.337554,...,0.519331,0.360168,0.423333,216,2,2,370,1,2019,130
4,13,495,0.433689,0.234218,0.285905,0.446732,0.201076,0.186178,0.107693,0.272928,...,0.473786,0.276693,0.421185,216,2,2,370,1,2019,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36059,20,495,0.375548,0.236551,0.206661,0.271642,0.111363,0.204372,0.198265,0.320443,...,0.218145,0.303726,0.270210,44751,2,2,370,2,2019,130
36060,30,495,0.790244,0.007290,0.106094,0.050211,0.044185,0.106026,0.034588,0.107066,...,0.040750,-0.015112,-0.010003,44751,2,2,370,2,2019,130
36061,31,495,0.158223,0.007290,0.106094,0.050211,0.044185,0.106026,0.034588,0.107066,...,0.040750,-0.015112,-0.010003,44751,2,2,370,2,2019,130
36062,32,495,0.158223,0.007290,0.106094,0.050211,0.044185,0.106026,0.034588,0.107066,...,0.040750,-0.015112,-0.010003,44751,2,2,370,2,2019,130
36063,235,495,0.158223,0.007290,0.106094,0.050211,0.044185,0.106026,0.034588,0.107066,...,0.040750,-0.015112,-0.010003,44751,2,2,370,2,2019,130

In [86]:
gbd_paf_small = pafs.loc[(pafs.age_group_id.isin([30,31,32,33])) & (pafs.location_id == 536)]
gbd_paf_small = gbd_paf_small.iloc[:,2:1002]
gbd_paf_small.std(axis=1)

6796    0.03771
6797    0.03771
6798    0.03771
6812    0.04189
6813    0.04189
6814    0.04189
dtype: float64

### Why are there Zeros? Test the Incidence First

In [67]:
def load_artifact_data(word:str, cause:str, measure:str, locations):
    master_art_data = pd.DataFrame()
    for i in locations: #in case there are other countries
        
        # grab main artifact object
        art = Artifact('/mnt/team/simulation_science/costeffectiveness/artifacts/vivarium_nih_us_cvd/51-locations/v1-20230613/' + i + '.hdf', 
                   filter_terms=['year_start == 2019', 'age_start >=  25']) # << MIGHT WANT TO CHANGE THESE TERMS
        
        # load requested measure
        data = art.load(word + '.' + cause + '.' + measure)
        
        # formatting (may want to format age as well)
        data['location'] = i#.capitalize()
        data['measure'] = measure
   
        #master_art_data = master_art_data.append(data)
        
    return data

In [72]:
art_inc = load_artifact_data('risk_factor', 'high_body_mass_index_in_adults', 'exposure', ['illinois'])
art_inc = art_inc.reset_index()

In [64]:
art_pop = art.load('risk_factor.high_body_mass_index_in_adults.tmred').reset_index()
art_pop

NameError: name 'art' is not defined

In [73]:
#art_inc = art_inc.drop(columns=['year_start','year_end'])
art_inc_small = art_inc[['sex','age_start','age_end','draw_1','draw_5']]
art_inc_small.loc[(art_inc_small.age_start > 75) ]

       sex  age_start  age_end     draw_1     draw_5
11  Female       80.0     85.0  29.117491  29.220001
12  Female       85.0     90.0  27.991359  28.171738
13  Female       90.0     95.0  27.619518  27.045626
14  Female       95.0    125.0  26.923581  27.261814
26    Male       80.0     85.0  28.622524  28.198301
27    Male       85.0     90.0  27.760074  27.674258
28    Male       90.0     95.0  27.196622  27.121978
29    Male       95.0    125.0  26.176856  26.742479

### Test to See if Means Match

In [ ]:
def test_mean_match(draws):
    for draw in draws: 
        for i in locations: 
            for j in risks: 
                subdata = pafs.loc[(pafs.location == i) & (pafs.risk == j)]
                loc = i
                risk = j
                if (subdata['draw_0'].mean() == subdata[draw].mean()):
                    print(loc,risk,draw)

In [ ]:
draw_test = ['draw_3','draw_13','draw_331','draw_687','draw_999']

In [ ]:
test_mean_match(draw_test)

### Test for Correct Affected Entities

In [ ]:
def test_entities(draws):
    for draw in draws: 
        for i in locations: 
            for j in risks: 
                subdata = pafs.loc[(pafs.location == i) & (pafs.risk == j)]
                loc = i
                risk = j
                affected_entities = subdata.reset_index()['affected_entity'].unique()
                if (risk == 'high_systolic_blood_pressure') | (risk == 'high_ldl_cholesterol'):
                    if not np.array_equiv(affected_entities, test_ent_ldl_sbp):
                        print(loc,risk,draw)
                if (risk == 'high_body_mass_index_in_adults'):
                    if not np.array_equiv(affected_entities, test_ent_bmi):
                        print(loc,risk,draw)

In [ ]:
draw_test = ['draw_0','draw_13','draw_331','draw_687','draw_999']
test_ent_bmi = ['acute_myocardial_infarction','post_myocardial_infarction_to_acute_myocardial_infarction','acute_ischemic_stroke','chronic_ischemic_stroke_to_acute_ischemic_stroke','heart_failure_from_ischemic_heart_disease','heart_failure_residual']
test_ent_sbp_cat = ['heart_failure_from_ischemic_heart_disease','heart_failure_residual']
test_ent_ldl_sbp = ['acute_myocardial_infarction','post_myocardial_infarction_to_acute_myocardial_infarction','acute_ischemic_stroke','chronic_ischemic_stroke_to_acute_ischemic_stroke']

In [ ]:
test_entities(draw_test)

## Checking Old PAFs vs New

In [ ]:
def load_old_artifact_data():
    master_art_data = pd.DataFrame()
    for i in locations:
        for j in risks:
            art = Artifact('/mnt/team/simulation_science/costeffectiveness/artifacts/vivarium_nih_us_cvd/' + i + '.hdf', 
                       filter_terms=['year_start == 2019', 'age_start >=  25']) # << MIGHT WANT TO CHANGE THESE TERMS
        
            data = art.load('risk_factor.' + j + '.population_attributable_fraction')
                
            # formatting (may want to format age as well)
            data['location'] = i
            data['risk'] = j
   
            master_art_data = master_art_data.append(data)
        
    return master_art_data

In [ ]:
old_pafs = load_old_artifact_data()
old_pafs.head()

In [ ]:
for j in risks: 
    plt.figure()
    subdata1 = pafs.loc[(pafs.location == 'alabama') & (pafs.risk == j)]
    subdata2 = old_pafs.loc[(old_pafs.location == 'alabama') & (old_pafs.risk == j)]
    plt.scatter(subdata1['draw_729'], subdata2['draw_729'], c = 'blue')
    plt.ylim(0,1)
    plt.xlim(0,1)
    plt.plot([0,1],[0,1])
    plt.title(f'PAFs Compared for {j}')

I have tried ~10 draws in the above code and am not seeing any type of consistent pattern between draws.